"""password validate error

Revision ID: 3d136c0123fa
Revises: 1afea83d71ee
Create Date: 2024-05-26 16:54:29.287772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d136c0123fa'
down_revision = '1afea83d71ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16277215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(length=16277215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
